version: '3.8'

services:
  snake-game:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./src:/usr/share/nginx/html
    restart: unless-stopped
